USE [master]
GO
/****** Object:  Database [farfar]    Script Date: 19/02/2018 09:16:43 p. m. ******/
DROP DATABASE [farfar]
GO
/****** Object:  Database [farfar]    Script Date: 19/02/2018 09:16:43 p. m. ******/
CREATE DATABASE [farfar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'farfar', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\farfar.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'farfar_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\farfar_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [farfar] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [farfar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [farfar] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [farfar] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [farfar] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [farfar] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [farfar] SET ARITHABORT OFF 
GO
ALTER DATABASE [farfar] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [farfar] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [farfar] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [farfar] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [farfar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [farfar] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [farfar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [farfar] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [farfar] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [farfar] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [farfar] SET  DISABLE_BROKER 
GO
ALTER DATABASE [farfar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [farfar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [farfar] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [farfar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [farfar] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [farfar] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [farfar] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [farfar] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [farfar] SET  MULTI_USER 
GO
ALTER DATABASE [farfar] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [farfar] SET DB_CHAINING OFF 
GO
ALTER DATABASE [farfar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [farfar] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [farfar] SET  READ_WRITE 
GO
